#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3 # All paddings use this value (icon, label, background)

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
cd $HOME/.config/sketchybar/helper && make
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload the macOS on screen indicator overlay for volume change
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

system_profiler SPDisplaysDataType | grep -q 'Resolution: 5120 x 1440'
# padding for ultrawide
if [[ $? -eq 0 ]]; then
    PADDING=1600
else
    PADDING=80
fi

# Setting up the general bar appearance and default values
bar=(
    blur_radius=20
    color=$BAR_COLOR
    corner_radius=9
    height=39
    margin=$PADDING
    notch_width=0
    padding_left=7
    padding_right=7
    position=bottom
    shadow=on
    sticky=on
    y_offset=6
)

default=(
    background.corner_radius=9
    background.height=26
    background.padding_left=$PADDINGS
    background.padding_right=$PADDINGS
    icon.color=$ICON_COLOR
    icon.font="$FONT:Bold:14.0"
    icon.padding_left=$PADDINGS
    icon.padding_right=$PADDINGS
    label.color=$LABEL_COLOR
    label.font="$FONT:Semibold:13.0"
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.border_width=2
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.background.corner_radius=11
    popup.background.shadow.drawing=on
    updates=when_shown
)

sketchybar --bar "${bar[@]}" --default "${default[@]}"

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/aerospace.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/divider.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/spotify.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
