if [ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]; then . $HOME/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

if [[ -f "$HOME/.local.zshrc" ]]
then
    source "$HOME/.local.zshrc"
fi

eval "$(fasd --init auto)"
